language: node_js
node_js:
  - '10.20.1'

script:
  - npm test
  - npm run build

jobs:
  include:
    - stage: 'npm Release'
      if: branch = master
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
